/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_FCClient */

#ifndef _Included_com_example_demo_FCClient
#define _Included_com_example_demo_FCClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_FCClient
 * Method:    eventHandle
 * Signature: (Lcom/example/demo/FCListener;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_demo_FCClient_eventHandle
  (JNIEnv *, jobject, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
